### ISSUE TITLE
error

### ISSUE THREAD

**Issue by roastbeef** [jonstewart/liblightgrep#1] opened 2013-06-04 00:03 UTC
Hello,

Trying to get lightgrep working for use with bulk extractor and keep getting this error while trying to make, on ubuntu. I have all the dependencies. 

Thanks

re_grammar.ypp: In function 'int yyparse({anonymous}::Context*)':
re_grammar.ypp:265:40: error: expected unqualified-id before numeric constant
re_grammar.ypp: In function 'int {anonymous}::consumeEscape({anonymous}::YYSTYPE*, {anonymous}::Context*)':
re_grammar.ypp:822:81: error: no matching function for call to 'consumeSingleton(<unresolved overloaded function type>, int, {anonymous}::YYSTYPE*&, {anonymous}::Context*&)'
re_grammar.ypp:822:81: note: candidate is:
re_grammar.ypp:682:7: note: template<class F> int {anonymous}::consumeSingleton(F, yytokentype, {anonymous}::YYSTYPE*, {anonymous}::Context*)
re_grammar.ypp:682:7: note:   template argument deduction/substitution failed:
re_grammar.ypp:822:81: note:   cannot convert '259' (type 'int') to type 'yytokentype'
re_grammar.ypp:825:76: error: no matching function for call to 'consumeSingleton(<unresolved overloaded function type>, int, {anonymous}::YYSTYPE*&, {anonymous}::Context*&)'
re_grammar.ypp:825:76: note: candidate is:
re_grammar.ypp:682:7: note: template<class F> int {anonymous}::consumeSingleton(F, yytokentype, {anonymous}::YYSTYPE*, {anonymous}::Context*)
re_grammar.ypp:682:7: note:   template argument deduction/substitution failed:
re_grammar.ypp:825:76: note:   cannot convert '259' (type 'int') to type 'yytokentype'
re_grammar.ypp:830:74: error: no matching function for call to 'consumeSingleton(<unresolved overloaded function type>, int, {anonymous}::YYSTYPE*&, {anonymous}::Context*&)'
re_grammar.ypp:830:74: note: candidate is:
re_grammar.ypp:682:7: note: template<class F> int {anonymous}::consumeSingleton(F, yytokentype, {anonymous}::YYSTYPE*, {anonymous}::Context*)
re_grammar.ypp:682:7: note:   template argument deduction/substitution failed:
re_grammar.ypp:830:74: note:   cannot convert '258' (type 'int') to type 'yytokentype'
re_grammar.ypp:842:74: error: no matching function for call to 'consumeSingleton(<unresolved overloaded function type>, int, {anonymous}::YYSTYPE*&, {anonymous}::Context*&)'
re_grammar.ypp:842:74: note: candidate is:
re_grammar.ypp:682:7: note: template<class F> int {anonymous}::consumeSingleton(F, yytokentype, {anonymous}::YYSTYPE*, {anonymous}::Context*)
re_grammar.ypp:682:7: note:   template argument deduction/substitution failed:
re_grammar.ypp:842:74: note:   cannot convert '259' (type 'int') to type 'yytokentype'
re_grammar.ypp:846:81: error: no matching function for call to 'consumeSingleton(<unresolved overloaded function type>, int, {anonymous}::YYSTYPE*&, {anonymous}::Context*&)'
re_grammar.ypp:846:81: note: candidate is:
re_grammar.ypp:682:7: note: template<class F> int {anonymous}::consumeSingleton(F, yytokentype, {anonymous}::YYSTYPE*, {anonymous}::Context*)
re_grammar.ypp:682:7: note:   template argument deduction/substitution failed:
re_grammar.ypp:846:81: note:   cannot convert '259' (type 'int') to type 'yytokentype'
make[1]: *** [src/lib/re_grammar.lo] Error 1
make[1]: Leaving directory `/home/bryan/liblightgrep'
make: *** [all] Error 2

**Comment by fsegna** [comment] 2015-01-08 09:18
Hi,
here is my re_grammar.cpp.
I cannot guarantee that my development environment has not been changed.
Anyway the error messages of make -j1 are the same.
Many thanks for your help
Franco

On Wed, Jan 7, 2015 at 2:02 PM, Joel Uckelman <notifications@github.com>
wrote:

> Would you attach your re_grammar.cpp? It's a generated file, so I can't
> tell by looking at mine what's in yours.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jonstewart/liblightgrep/issues/1#issuecomment-69018571>
> .
>



-- 
Franco Segna
via Dante 60  -  31027 Spresiano TV  -  Italia
phone +39 0422 725020  -  fax +39 0422 888707

**Comment by ch-sirius** [comment] 2015-01-13 14:31
Hi there,
I just had the same issue (Ubuntu 14.04). 
The installation worked after rebooting the os and recloneing the repo.
Maybe, it helps for you, too.

**Comment by jonstewart** [comment] 2015-01-14 14:58
This is weird, because I'm using Mint 17, which is based on Ubuntu 14.04. Two other questions:

1. How are you downloading liblightgrep initially (when it fails)?

2. If you're downloading as a git repository, can you tell us the commit number?
   a. first run "git status" in the liblightgrep directory and post the results here
   b. assuming that says "On branch master" on the first line, then run "git show HEAD" and post the results here.

Thanks!

**Comment by uckelman** [comment] 2015-01-14 15:16
Thus spake fsegna:
> Hi,
> here is my re_grammar.cpp.
> I cannot guarantee that my development environment has not been changed.
> Anyway the error messages of make -j1 are the same.
> Many thanks for your help
> Franco

It looks like the file didn't get attached. Try again?

-- 
J.

**Comment by fsegna** [comment] 2015-01-14 17:53
Voilà:

fsegna@Forensics-3:~/Sviluppo$ *git clone
https://github.com/jonstewart/liblightgrep.git
<https://github.com/jonstewart/liblightgrep.git>*
Cloning into 'liblightgrep'...
remote: Counting objects: 13712, done.
remote: Total 13712 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (13712/13712), 169.36 MiB | 194.00 KiB/s, done.
Resolving deltas: 100% (9901/9901), done.
Checking connectivity... done.
fsegna@Forensics-3:~/Sviluppo$ cd liblightgrep
fsegna@Forensics-3:~/Sviluppo/liblightgrep$ *git status*
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
fsegna@Forensics-3:~/Sviluppo/liblightgrep$ *git show HEAD*
commit 4005d584884bdb7fceaadfd9210b7f02865ffb93
Author: Joel Uckelman <uckelman@nomic.net>
Date:   Thu Nov 20 14:42:30 2014 +0000

    Bumped version to 1.4.1.

diff --git a/configure.ac b/configure.ac
index 47ea1ed..0c16f74 100644
--- a/configure.ac
+++ b/configure.ac
@@ -3,7 +3,7 @@
 AC_PREREQ([2.64])
 # TODO: required versions for automake, libtool?

-AC_INIT([liblightgrep], [1.3.0], [joel@lightboxtechnologies.com])
+AC_INIT([liblightgrep], [1.5.0], [joel@lightboxtechnologies.com])

 # Set the default C and C++ compilation flags to nothing.
 # Do this immediately after AC_INIT, as other macros might invoke


On Wed, Jan 14, 2015 at 3:58 PM, Jon Stewart <notifications@github.com>
wrote:

> This is weird, because I'm using Mint 17, which is based on Ubuntu 14.04.
> Two other questions:
>
>    1.
>
>    How are you downloading liblightgrep initially (when it fails)?
>    2.
>
>    If you're downloading as a git repository, can you tell us the commit
>    number?
>    a. first run "git status" in the liblightgrep directory and post the
>    results here
>    b. assuming that says "On branch master" on the first line, then run
>    "git show HEAD" and post the results here.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jonstewart/liblightgrep/issues/1#issuecomment-69927808>
> .
>



-- 
Franco Segna
via Dante 60  -  31027 Spresiano TV  -  Italia
phone +39 0422 725020  -  fax +39 0422 888707

**Comment by fsegna** [comment] 2015-01-14 18:03
... and today the compilation was successful !!!
Sorry, I'm only a beginner, unable to contribute to your excellent work.
liblightgrep is a fantastic piece of software for us forensic investigators.
Thanks again
Franco

On Wed, Jan 14, 2015 at 6:52 PM, franco segna <fsegna@gmail.com> wrote:

> Voilà:
>
> fsegna@Forensics-3:~/Sviluppo$ *git clone
> https://github.com/jonstewart/liblightgrep.git
> <https://github.com/jonstewart/liblightgrep.git>*
> Cloning into 'liblightgrep'...
> remote: Counting objects: 13712, done.
> remote: Total 13712 (delta 0), reused 0 (delta 0)
> Receiving objects: 100% (13712/13712), 169.36 MiB | 194.00 KiB/s, done.
> Resolving deltas: 100% (9901/9901), done.
> Checking connectivity... done.
> fsegna@Forensics-3:~/Sviluppo$ cd liblightgrep
> fsegna@Forensics-3:~/Sviluppo/liblightgrep$ *git status*
> On branch master
> Your branch is up-to-date with 'origin/master'.
>
> nothing to commit, working directory clean
> fsegna@Forensics-3:~/Sviluppo/liblightgrep$ *git show HEAD*
> commit 4005d584884bdb7fceaadfd9210b7f02865ffb93
> Author: Joel Uckelman <uckelman@nomic.net>
> Date:   Thu Nov 20 14:42:30 2014 +0000
>
>     Bumped version to 1.4.1.
>
> diff --git a/configure.ac b/configure.ac
> index 47ea1ed..0c16f74 100644
> --- a/configure.ac
> +++ b/configure.ac
> @@ -3,7 +3,7 @@
>  AC_PREREQ([2.64])
>  # TODO: required versions for automake, libtool?
>
> -AC_INIT([liblightgrep], [1.3.0], [joel@lightboxtechnologies.com])
> +AC_INIT([liblightgrep], [1.5.0], [joel@lightboxtechnologies.com])
>
>  # Set the default C and C++ compilation flags to nothing.
>  # Do this immediately after AC_INIT, as other macros might invoke
>
>
> On Wed, Jan 14, 2015 at 3:58 PM, Jon Stewart <notifications@github.com>
> wrote:
>
>> This is weird, because I'm using Mint 17, which is based on Ubuntu 14.04.
>> Two other questions:
>>
>>    1.
>>
>>    How are you downloading liblightgrep initially (when it fails)?
>>    2.
>>
>>    If you're downloading as a git repository, can you tell us the commit
>>    number?
>>    a. first run "git status" in the liblightgrep directory and post the
>>    results here
>>    b. assuming that says "On branch master" on the first line, then run
>>    "git show HEAD" and post the results here.
>>
>> Thanks!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jonstewart/liblightgrep/issues/1#issuecomment-69927808>
>> .
>>
>
>
>
> --
> Franco Segna
> via Dante 60  -  31027 Spresiano TV  -  Italia
> phone +39 0422 725020  -  fax +39 0422 888707
>
>


-- 
Franco Segna
via Dante 60  -  31027 Spresiano TV  -  Italia
phone +39 0422 725020  -  fax +39 0422 888707

**Comment by jonstewart** [comment] 2015-01-15 01:18
Great. Let us know if you run into it again and can reproduce. Thanks!

**Closed by jonstewart** 2015-01-15 01:18 UTC
